//
// Created by marij on 9/15/2023.
//

#ifndef ADVANCED_PROGRAMMING_CONCEPTS_1_CLOGGER_ADAPTER_H
#define ADVANCED_PROGRAMMING_CONCEPTS_1_CLOGGER_ADAPTER_H


class clogger_adapter {

};


#endif //ADVANCED_PROGRAMMING_CONCEPTS_1_CLOGGER_ADAPTER_H
